### ISSUE TITLE
Обязательный вызов конструктора родителя в конструкторе дочернего класса

### ISSUE THREAD

**Issue by Riim** [yandex/codestyle#31]
```js
funcion Emitter() {
  this._events = {};
}

function Child() {
  Emitter.call(this);

  // ...
}
```

Обязательно вызывать конструктор родителя в дочерних классах, даже если он пустой. Во-первых, если он вдруг станет не пустым, прийдётся перетрахать всех детей (добавляя этот вызов), во-вторых, не всегда вообще будет такая возможность, например, либа уже юзается в разных проектах, и вдруг в конструктор понадобилось что-то добавить. Если при этом дока либы не требовала такого вызова, то придётся извращаться в каждом методе как-то так:
```js
Emitter.prototype.addListener = function(type, listener, context) {
  var events = this._events || (this._events = {});

  // ...
};
```
Хотя это может и так оказаться полезным, например, если класс должен иметь возможность использоваться как примесь, но в большинстве случаев это не удобно.  
Ещё можно учесть, что иногда классы в js используются как интерфейсы. Для таких классов можно убрать это требование, но добавить какое-то требование по неймингу, например `I` перед именем: `IDisposable`.

**Comment by tarmolov** [comment]
На мой взгляд это не относится к кодстайлу. 

Это больше про практики, принятые в рамках отдельно взятой команды.
В другой команде, например, наследование может быть упразднено в пользу композиции ;)
